import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import Header from '../components/Header'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <h1>Hello World!</h1>
      <Link href="/apollo-test"><a>GQL Test</a></Link>
      <Link href="/writing"><a>Writing</a></Link>

    </div>
  )
}
